# Generated by Django 3.1.7 on 2021-04-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('SAC', 'SINGLE AC'), ('SNAC', 'SINGLE NON-AC'), ('DAC', 'DOUBLE AC'), ('DNAC', 'DOUBLE NON-AC'), ('TAC', 'TRIPLE AC'), ('TNAC', 'TRIPLE NON-AC'), ('DRAC', 'DOUBLE ROOM AC'), ('DRNAC', 'DOUBLE ROOM NON-AC'), ('FAM', 'FAMILY AC'), ('KING', 'KING AC'), ('DDAC', 'DOUBLE-DOUBLE AC'), ('STU', 'STUDIO'), ('VIP', 'PRESIDENT SUITE')], max_length=5)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='royalvillas_home',
        ),
    ]
