# Generated by Django 2.0.13 on 2021-04-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
