# Generated by Django 2.0.13 on 2021-04-23 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('py_django_app', '0004_auto_20210422_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('SAC', 'SINGLE AC'), ('SNAC', 'SINGLE NON-AC'), ('DAC', 'DOUBLE AC'), ('DNAC', 'DOUBLE NON-AC'), ('TAC', 'TRIPLE AC'), ('TNAC', 'TRIPLE NON-AC'), ('DRAC', 'DOUBLE ROOM AC'), ('DRNAC', 'DOUBLE ROOM NON-AC'), ('FAM', 'FAMILY AC'), ('KING', 'KING AC'), ('DDAC', 'DOUBLE-DOUBLE AC'), ('STU', 'STUDIO'), ('VIP', 'PRESIDENT SUITE')], max_length=5)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_django_app.Rooms'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
