# Generated by Django 2.0.13 on 2021-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0005_auto_20210423_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='category',
            new_name='R_category',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='beds',
            new_name='rooms_number',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='number',
        ),
        migrations.AddField(
            model_name='rooms',
            name='P_category',
            field=models.CharField(choices=[('RVC', 'ROYAL VILLAS, CHENNAI'), ('RVB', 'ROYAL VILLAS, BANGALORE'), ('RVH', 'ROYAL VILLAS, HYDERABAD'), ('RVD', 'ROYAL VILLAS, DELHI'), ('RVK', 'ROYAL VILLAS, KOLKATA')], default=2, max_length=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
