# Generated by Django 2.0.13 on 2021-04-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0006_auto_20210423_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomsdetails', models.CharField(max_length=200)),
                ('adultsdetails', models.CharField(max_length=200)),
                ('childrendetails', models.CharField(max_length=200)),
                ('checkindetails', models.DateTimeField()),
                ('checkoutdetails', models.DateTimeField()),
                ('namedetails', models.CharField(max_length=200)),
                ('phonedetails', models.IntegerField(max_length=50)),
                ('emaildetails', models.CharField(max_length=200)),
                ('moredetails', models.CharField(max_length=200)),
            ],
        ),
    ]
