# Generated by Django 2.0.13 on 2021-04-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0007_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonedetails',
            field=models.IntegerField(),
        ),
    ]
