# Generated by Django 2.0.13 on 2021-04-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0008_auto_20210424_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkindetails',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkoutdetails',
            field=models.DateField(),
        ),
    ]
