# Generated by Django 2.0.13 on 2021-04-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0009_auto_20210424_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='adultsdetails',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='childrendetails',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='emaildetails',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='moredetails',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='namedetails',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phonedetails',
            field=models.IntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='roomsdetails',
            field=models.CharField(max_length=50),
        ),
    ]
