# Generated by Django 2.0.13 on 2021-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0010_auto_20210424_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phonedetails',
            field=models.CharField(max_length=12),
        ),
    ]
