# Generated by Django 2.0.13 on 2021-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0012_auto_20210424_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkintime',
            field=models.TimeField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkouttime',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='adultsdetails',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkindetails',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkoutdetails',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='childrendetails',
            field=models.IntegerField(),
        ),
    ]
