# Generated by Django 2.0.13 on 2021-04-24 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0013_auto_20210424_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkintime',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkouttime',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
    ]
