# Generated by Django 2.0.13 on 2021-04-24 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0015_auto_20210424_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkintime',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkouttime',
        ),
    ]
