# Generated by Django 2.0.13 on 2021-04-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0016_auto_20210424_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkindetails',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkoutdetails',
            field=models.DateTimeField(),
        ),
    ]
