# Generated by Django 2.0.13 on 2021-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0017_auto_20210424_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkindetails',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkoutdetails',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
