# Generated by Django 2.0.13 on 2021-04-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0020_auto_20210424_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkindetails',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkoutdetails',
        ),
    ]
