# Generated by Django 2.0.13 on 2021-04-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0021_auto_20210424_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomsdetails', models.CharField(default='test', max_length=50, null=True)),
                ('adultsdetails', models.IntegerField()),
                ('childrendetails', models.IntegerField()),
                ('checkindetails', models.DateField()),
                ('checkoutdetails', models.DateField()),
                ('namedetails', models.CharField(default='test', max_length=50, null=True)),
                ('phonedetails', models.CharField(default='test', max_length=50, null=True)),
                ('emaildetails', models.CharField(default='test', max_length=50, null=True)),
                ('moredetails', models.CharField(default='test', max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
