# Generated by Django 2.0.13 on 2021-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0022_auto_20210424_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='checkintime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='checkouttime',
            field=models.TimeField(null=True),
        ),
    ]
