# Generated by Django 2.0.13 on 2021-04-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0023_auto_20210424_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkintime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkouttime',
            field=models.TimeField(),
        ),
    ]
