# Generated by Django 2.0.13 on 2021-04-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0025_auto_20210424_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkintime',
        ),
        migrations.RemoveField(
            model_name='book',
            name='checkouttime',
        ),
    ]
