# Generated by Django 2.0.13 on 2021-04-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0027_auto_20210424_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='checkintime',
            new_name='checkin_time',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='checkouttime',
            new_name='checkout_time',
        ),
    ]
