# Generated by Django 2.0.13 on 2021-04-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0028_auto_20210424_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='checkin_time',
        ),
        migrations.RemoveField(
            model_name='book',
            name='checkout_time',
        ),
        migrations.AlterField(
            model_name='book',
            name='checkindetails',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkoutdetails',
            field=models.DateTimeField(),
        ),
    ]
