# Generated by Django 2.0.13 on 2021-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0029_auto_20210424_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkindetails',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkoutdetails',
            field=models.DateField(),
        ),
    ]
