# Generated by Django 2.0.13 on 2021-04-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0030_auto_20210425_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkindetails',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkoutdetails',
            field=models.DateTimeField(),
        ),
    ]
