# Generated by Django 2.0.13 on 2021-04-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0031_auto_20210425_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='placedetails',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
    ]
