# Generated by Django 2.0.13 on 2021-04-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0032_book_placedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_category', models.CharField(choices=[('RVC', 'ROYAL VILLAS, CHENNAI'), ('RVB', 'ROYAL VILLAS, BANGALORE'), ('RVH', 'ROYAL VILLAS, HYDERABAD'), ('RVD', 'ROYAL VILLAS, DELHI'), ('RVK', 'ROYAL VILLAS, KOLKATA')], max_length=5)),
                ('R_category', models.CharField(choices=[('SAC', 'SINGLE AC'), ('SNAC', 'SINGLE NON-AC'), ('DAC', 'DOUBLE AC'), ('DNAC', 'DOUBLE NON-AC'), ('TAC', 'TRIPLE AC'), ('TNAC', 'TRIPLE NON-AC'), ('DRAC', 'DOUBLE ROOM AC'), ('DRNAC', 'DOUBLE ROOM NON-AC'), ('FAM', 'FAMILY AC'), ('KING', 'KING AC'), ('DDAC', 'DOUBLE-DOUBLE AC'), ('STU', 'STUDIO'), ('VIP', 'PRESIDENT SUITE')], max_length=5)),
                ('rooms_number', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
