# Generated by Django 2.0.13 on 2021-04-26 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0033_auto_20210425_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_django_app.Room'),
        ),
    ]
