# Generated by Django 2.0.13 on 2021-04-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0034_auto_20210426_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.CharField(default='test', max_length=50, null=True),
        ),
    ]
