# Generated by Django 2.0.13 on 2021-04-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0035_auto_20210426_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkindetails',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkoutdetails',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateField(),
        ),
    ]
