# Generated by Django 2.0.13 on 2021-04-26 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0036_auto_20210426_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='rooms_number',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='room',
            name='check_out',
        ),
        migrations.AlterField(
            model_name='book',
            name='placedetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='py_django_app_book_ownership', to='py_django_app.Room'),
        ),
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_django_app.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='P_category',
            field=models.CharField(choices=[('RVC', 'ROYAL VILLAS, CHENNAI'), ('RVB', 'ROYAL VILLAS, BANGALORE'), ('RVH', 'ROYAL VILLAS, HYDERABAD'), ('RVD', 'ROYAL VILLAS, DELHI'), ('RVK', 'ROYAL VILLAS, KOLKATA')], max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='R_category',
            field=models.CharField(choices=[('SAC', 'SINGLE AC'), ('SNAC', 'SINGLE NON-AC'), ('DAC', 'DOUBLE AC'), ('DNAC', 'DOUBLE NON-AC'), ('TAC', 'TRIPLE AC'), ('TNAC', 'TRIPLE NON-AC'), ('DRAC', 'DOUBLE ROOM AC'), ('DRNAC', 'DOUBLE ROOM NON-AC'), ('FAM', 'FAMILY AC'), ('KING', 'KING AC'), ('DDAC', 'DOUBLE-DOUBLE AC'), ('STU', 'STUDIO'), ('VIP', 'PRESIDENT SUITE')], max_length=50),
        ),
    ]
