# Generated by Django 2.0.13 on 2021-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0037_auto_20210426_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='placedetails',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.CharField(max_length=50),
        ),
    ]
