# Generated by Django 2.0.13 on 2021-04-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0038_auto_20210426_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='test', max_length=30)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.IntegerField()),
                ('country', models.CharField(choices=[('India', 'India'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Russia', 'Russia'), ('United Kingdom', 'UK'), ('United States', 'US')], max_length=20)),
                ('feedback', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='moredetails',
            field=models.CharField(default='nothing', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='placedetails',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.CharField(max_length=5),
        ),
    ]
