# Generated by Django 3.2 on 2021-04-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0039_auto_20210426_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='phonedetails',
            field=models.CharField(default='test', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
