# Generated by Django 3.2 on 2021-04-26 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0040_auto_20210426_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Comment',
        ),
    ]
