# Generated by Django 3.2 on 2021-04-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0044_auto_20210426_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Russia', 'Russia'), ('United Kingdom', 'UK'), ('United States', 'US')], default='test', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='test', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='feedback',
            field=models.CharField(default='test', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='test', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='test', max_length=20, null=True),
        ),
    ]
