# Generated by Django 3.2 on 2021-04-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0047_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='number', max_length=20, null=True),
        ),
    ]
