# Generated by Django 3.2 on 2021-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0048_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
