# Generated by Django 3.2 on 2021-04-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0050_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Russia', 'Russia'), ('United Kingdom', 'UK'), ('United States', 'US')], max_length=20),
        ),
    ]
