# Generated by Django 3.2 on 2021-04-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0051_alter_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='emaildetails',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='moredetails',
            field=models.CharField(default='nothing', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='namedetails',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='phonedetails',
            field=models.CharField(default='test', max_length=12),
        ),
    ]
