# Generated by Django 3.2 on 2021-04-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0052_auto_20210427_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='test', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='feedback',
            field=models.CharField(default='test', max_length=300),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='number', max_length=20),
        ),
    ]
