# Generated by Django 3.2 on 2021-04-27 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0053_auto_20210427_0709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
