# Generated by Django 3.2 on 2021-04-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0054_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='test', max_length=30)),
                ('first_name', models.CharField(default='test', max_length=20)),
                ('last_name', models.CharField(default='test', max_length=20)),
                ('phone_number', models.CharField(default='number', max_length=20)),
                ('country', models.CharField(choices=[('India', 'India'), ('France', 'France'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Russia', 'Russia'), ('United Kingdom', 'UK'), ('United States', 'US')], max_length=20)),
                ('feedback', models.CharField(default='test', max_length=300)),
            ],
        ),
    ]
