# Generated by Django 3.2 on 2021-04-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0055_contact'),
    ]

    operations = [
    ]
