# Generated by Django 3.2 on 2021-04-27 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0056_auto_20210427_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adultsdetails',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='book',
            name='childrendetails',
            field=models.IntegerField(default='0'),
        ),
    ]
