# Generated by Django 3.2 on 2021-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0057_auto_20210427_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='R_category',
            field=models.CharField(choices=[('SAC', 'SINGLE AC'), ('SNAC', 'SINGLE NON-AC'), ('DAC', ' DOUBLE AC'), ('DNAC', 'DOUBLE NON-AC'), ('TAC', 'TRIPLE AC'), ('TNAC', 'TRIPLE NON-AC'), ('DRAC', 'DOUBLE ROOM AC'), ('DRNAC', 'DOUBLE ROOM NON-AC'), ('FAM', 'FAMILY AC'), ('KING', 'KING AC'), ('DDAC', 'DOUBLE-DOUBLE AC'), ('STU', 'STUDIO'), ('VIP', 'PRESIDENT SUITE')], max_length=50),
        ),
    ]
