# Generated by Django 3.2 on 2021-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0058_alter_room_r_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='P_category',
            field=models.CharField(choices=[('ROYAL VILLAS, CHENNAI', 'ROYAL VILLAS, CHENNAI'), ('ROYAL VILLAS, BANGALORE', 'ROYAL VILLAS, BANGALORE'), ('ROYAL VILLAS, HYDERABAD', 'ROYAL VILLAS, HYDERABAD'), ('ROYAL VILLAS, DELHI', 'ROYAL VILLAS, DELHI'), ('ROYAL VILLAS, KOLKATA', 'ROYAL VILLAS, KOLKATA')], max_length=50),
        ),
    ]
