# Generated by Django 3.2 on 2021-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0059_alter_room_p_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='R_category',
            field=models.CharField(choices=[('SINGLE AC', 'SINGLE AC'), ('SINGLE NON-AC', 'SINGLE NON-AC'), ('DOUBLE AC', ' DOUBLE AC'), ('DOUBLE NON-AC', 'DOUBLE NON-AC'), ('TRIPLE AC', 'TRIPLE AC'), ('TRIPLE NON-AC', 'TRIPLE NON-AC'), ('DOUBLE ROOM AC', 'DOUBLE ROOM AC'), ('DOUBLE ROOM NON-AC', 'DOUBLE ROOM NON-AC'), ('FAMILY AC', 'FAMILY AC'), ('KING AC', 'KING AC'), ('DOUBLE-DOUBLE AC', 'DOUBLE-DOUBLE AC'), ('STUDIO', 'STUDIO'), ('PRESIDENT SUITE', 'PRESIDENT SUITE')], max_length=50),
        ),
    ]
