# Generated by Django 3.2 on 2021-04-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0060_alter_room_r_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='P_category',
            field=models.CharField(choices=[('ROYAL VILLAS, CHENNAI', 'ROYAL VILLAS, CHENNAI'), ('ROYAL VILLAS, BANGALORE', 'ROYAL VILLAS, BANGALORE'), ('ROYAL VILLAS, HYDERABAD', 'ROYAL VILLAS, HYDERABAD'), ('ROYAL VILLAS, DELHI', 'ROYAL VILLAS, DELHI'), ('ROYAL VILLAS, KOLKATA', 'ROYAL VILLAS, KOLKATA')], max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='R_category',
            field=models.CharField(choices=[('SINGLE AC', 'SINGLE AC'), ('SINGLE NON-AC', 'SINGLE NON-AC'), ('DOUBLE AC', ' DOUBLE AC'), ('DOUBLE NON-AC', 'DOUBLE NON-AC'), ('TRIPLE AC', 'TRIPLE AC'), ('TRIPLE NON-AC', 'TRIPLE NON-AC'), ('DOUBLE ROOM AC', 'DOUBLE ROOM AC'), ('DOUBLE ROOM NON-AC', 'DOUBLE ROOM NON-AC'), ('FAMILY AC', 'FAMILY AC'), ('KING AC', 'KING AC'), ('DOUBLE-DOUBLE AC', 'DOUBLE-DOUBLE AC'), ('STUDIO', 'STUDIO'), ('PRESIDENT SUITE', 'PRESIDENT SUITE')], max_length=100),
        ),
    ]
