# Generated by Django 3.2 on 2021-04-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0061_auto_20210428_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='py_django_app.room'),
        ),
    ]
