# Generated by Django 3.2 on 2021-04-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0062_alter_book_roomsdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='placedetails',
        ),
        migrations.RemoveField(
            model_name='room',
            name='P_category',
        ),
    ]
