# Generated by Django 3.2 on 2021-04-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0063_auto_20210429_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='roomsdetails',
            field=models.CharField(max_length=50),
        ),
    ]
