# Generated by Django 3.2 on 2021-04-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0064_alter_book_roomsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='checkindetails',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='checkoutdetails',
            field=models.DateTimeField(),
        ),
    ]
