# Generated by Django 3.2 on 2021-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0065_auto_20210429_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default='0'),
        ),
    ]
