# Generated by Django 3.2 on 2021-04-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0066_auto_20210429_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='py_django_app.room'),
            preserve_default=False,
        ),
    ]
