# Generated by Django 3.2 on 2021-04-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0067_book_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='room',
        ),
    ]
