# Generated by Django 3.2 on 2021-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0068_remove_book_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default='True'),
        ),
    ]
