# Generated by Django 3.2 on 2021-04-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0070_alter_room_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
