# Generated by Django 3.2 on 2021-05-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('py_django_app', '0074_auto_20210506_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='comment_type',
            field=models.CharField(choices=[('Request', 'Request'), ('Comment', 'Comment')], default=type, max_length=20),
            preserve_default=False,
        ),
    ]
